Config:
  TeleportOnJoin: false
  DisableBlockBreak: true
  DisableBlockPlace: true
  DisablePVP: true
  DisableDamage: true
  WelcomeMessageB: false
  JoinMessageB: true
  LeaveMessageB: true
  FireworkOnJoin: true
  TeleportOnRespawn: true
  DisableHunger: true
  DisableWeatherChange: true
Messages:
  WelcomeMessage: 'Hallo'
  JoinMessage: '&a[+] &6%player% joined the server'
  LeaveMessage: '&c[-] &6%player% left the server'
  PlaceBlocksMessage:'NEIN'
  BreakBlocksMessage: '&cNEIN'
  PlayerHitMessage: '&cPVP is here disabled!'
  Prefix: '&bSimpleLobby '
  SpawnTeleportMessage: '&aTeleported to spawn!'
Scoreboard:
  isEnabled: true
  onlyInLobbyWorld: true
  Title: '&b&lHUB'
  line0: ' '
  line1: 'Hallo'
  line2: ' '
  line3: ''
  line4: ''
  line5: ''
  line6: ''
  line7: ''
  line8: ''
  line9: ''
  line10: 'SERVER²'
Bossbar:
  isEnabled: true
  onlyInLobbyWorld: true
  Color: blue
  Text: '&b&lSimpleLobby'
Commands:
  SpawnTeleport: true
